// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Account struct {
	ID       int32
	Username string
}

type LoginInfo struct {
	ID           int32
	AccountID    int32
	PasswordHesh string
}

type Profile struct {
	ID       int32
	Name     string
	LastName string
	Age      int16
}
