// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (name, last_name, age)
VALUES ($1, $2, $3)
RETURNING id, name, last_name, age
`

type CreateProfileParams struct {
	Name     string
	LastName string
	Age      int16
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.Name, arg.LastName, arg.Age)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Age,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :one
DELETE FROM profiles
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteProfile(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteProfile, id)
	err := row.Scan(&id)
	return id, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, last_name, age from profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id int32) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Age,
	)
	return i, err
}

const patchProfile = `-- name: PatchProfile :one
UPDATE profiles
    SET name = COALESCE($2, name),
    last_name = COALESCE($3, last_name),
    age = COALESCE($4, age)
WHERE id = $1
RETURNING id, name, last_name, age
`

type PatchProfileParams struct {
	ID       int32
	Name     *string
	LastName *string
	Age      *int16
}

func (q *Queries) PatchProfile(ctx context.Context, arg PatchProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, patchProfile,
		arg.ID,
		arg.Name,
		arg.LastName,
		arg.Age,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Age,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
    SET name = $2,
    last_name = $3,
    age = $4
WHERE id = $1
RETURNING id, name, last_name, age
`

type UpdateProfileParams struct {
	ID       int32
	Name     string
	LastName string
	Age      int16
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.LastName,
		arg.Age,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Age,
	)
	return i, err
}
